import { createContext, useContext, useState, ReactNode } from 'react'

export type Lang = 'es' | 'en'

export const translations = {
  es: {
    // ── Navigation ────────────────────────────────────────────────────────────
    nav_dashboard:   'Dashboard',
    nav_manual:      'Panel Manual',
    nav_signals:     'Señales',
    nav_orders:      'Órdenes',
    nav_reports:     'Reportes',
    nav_groups:      'Grupos de copia',
    nav_accounts:    'Cuentas',
    nav_rules:       'Reglas de riesgo',
    nav_webhook:     'Webhook / TV',
    nav_notifications: 'Notificaciones',
    nav_plans:       'Planes',
    nav_admin:       'Admin',
    nav_config:      'Configuración',
    nav_change_pwd:  'Cambiar contraseña',
    nav_logout:      'Cerrar sesión',

    // ── TopActionBar section titles ────────────────────────────────────────────
    section_dashboard_title:    'Dashboard',
    section_dashboard_sub:      'Resumen de cuentas, señales y ejecución',
    section_signals_title:      'Señales',
    section_signals_sub:        'Entradas recibidas y trazabilidad por evento',
    section_orders_title:       'Bitácora',
    section_orders_sub:         'Historial de ejecución por cuenta y grupo',
    section_manual_title:       'Panel Manual',
    section_manual_sub:         'Gestiona órdenes manuales pendientes',
    section_reports_title:      'Reportes',
    section_reports_sub:        'Métricas de rendimiento y calidad de ejecución',
    section_settings_title:     'Notificaciones',
    section_settings_sub:       'Canales, alertas y preferencias',
    section_groups_title:       'Copy Groups',
    section_groups_sub:         'Grupos de copia y distribución de señales',
    section_accounts_title:     'Cuentas',
    section_accounts_sub:       'Conexión y configuración de cuentas de broker',
    section_rules_title:        'Reglas de riesgo',
    section_rules_sub:          'Límites de exposición y gestión de posición',
    section_webhook_title:      'Webhook / TV',
    section_webhook_sub:        'Configuración de fuentes de señal externas',
    section_plans_title:        'Planes',
    section_plans_sub:          'Configuración de suscripción y límites',
    section_admin_title:        'Admin',
    section_admin_sub:          'Configuración del sistema y usuarios',

    // ── Health states ─────────────────────────────────────────────────────────
    health_ok:       'Sistema estable',
    health_degraded: 'Modo degradado',
    health_down:     'API sin respuesta',
    health_checking: 'Verificando...',
    last_signal_label: 'Última señal',

    // ── Common ────────────────────────────────────────────────────────────────
    save:            'Guardar',
    cancel:          'Cancelar',
    close:           'Cerrar',
    delete:          'Eliminar',
    edit:            'Editar',
    new:             'Nuevo',
    update:          'Actualizar',
    loading:         'Cargando...',
    no_data:         'Sin datos',
    error:           'Error',
    success:         'Éxito',
    refresh:         'Refrescar',
    refreshing:      'Actualizando...',
    saving:          'Guardando...',
    saved:           'Guardado',
    confirm_delete:  'Confirmar eliminación',
    cannot_undo:     'Esta acción no se puede deshacer.',
    are_you_sure:    '¿Estás seguro de que quieres eliminar esta cuenta?',
    previous:        'Anterior',
    next:            'Siguiente',
    page:            'Página',
    all:             'Todos',
    all_f:           'Todas',
    active:          'Activo',
    inactive:        'Inactivo',
    status:          'Estado',
    name:            'Nombre',
    type:            'Tipo',
    environment:     'Entorno',
    balance:         'Balance',
    actions:         'Acciones',
    send:            'Enviar',
    connect:         'Conectar',
    sending:         'Enviando...',
    updated:         'Actualizado',
    see_all:         'Ver todas →',
    see_history:     'Ver historial →',
    create_account:  'Crear cuenta',
    add:             'Agregar',

    // ── Status badges ─────────────────────────────────────────────────────────
    status_active:    'Activa',
    status_inactive:  'Inactiva',
    status_paused:    'Pausada',
    status_no_token:  'Sin token',
    status_connected: 'Conectada',
    status_filled:    'Ejecutada',
    status_pending:   'En cola',
    status_sent:      'Enviada',
    status_skipped:   'Saltada',
    status_error:     'Error',
    status_open:      'ABIERTA',
    status_closed:    'CERRADA',
    status_awaiting:  'PENDIENTE',
    status_rejected:  'Rechazada',

    // ── Dashboard ─────────────────────────────────────────────────────────────
    dash_day_summary:     'Resumen del día',
    dash_updated_at:      'Actualizado',
    dash_manual_panel:    '+ Panel manual',
    dash_kpi_active_accs: 'Cuentas activas',
    dash_kpi_active_sub:  'Listas para operar',
    dash_kpi_signals:     'Señales hoy',
    dash_kpi_signals_sub: 'Entradas recibidas',
    dash_kpi_orders:      'Órdenes ejecutadas',
    dash_kpi_orders_sub:  'Filled en el día',
    dash_kpi_pnl:         'P&L del día',
    dash_kpi_pnl_pos:     'Sesgo positivo',
    dash_kpi_pnl_neg:     'Sesgo negativo',
    dash_accounts_title:  'Cuentas y conexión',
    dash_signals_title:   'Señales recientes',
    dash_no_accounts:     'Sin cuentas configuradas',
    dash_no_signals:      'Aún no hay señales recientes.',
    dash_alert_paused:    'Cuentas pausadas por riesgo',
    dash_alert_no_token:  'Cuentas sin conexión de broker',
    dash_alert_no_accs:   'No hay cuentas configuradas',
    dash_alert_no_accs_body: 'Crea una cuenta para empezar a procesar señales.',

    // ── Accounts ─────────────────────────────────────────────────────────────
    acc_title:           'Cuentas',
    acc_new:             '+ Nueva cuenta',
    acc_tv_user:         'Usuario TV',
    acc_stage:           'Etapa',
    acc_no_accounts:     'No hay cuentas. Crea una nueva cuenta para comenzar.',
    acc_edit_title:      'Editar cuenta',
    acc_new_title:       'Nueva cuenta',
    acc_name_label:      'Nombre *',
    acc_type_label:      'Tipo de cuenta',
    acc_paper_title:     'Paper Trading',
    acc_paper_sub:       'Sin broker real · Inmediato',
    acc_tv_requires:     'Requiere OAuth',
    acc_balance_label:   'Balance inicial ($)',
    acc_paper_note:      'Cuenta simulada — las órdenes se ejecutan instantáneamente sin broker real.',
    acc_tv_username:     'Usuario / Email Tradovate',
    acc_account_number:  'Número de Cuenta',
    acc_account_number_hint: 'ID numérico en Tradovate',
    acc_account_spec:    'Account Spec',
    acc_apex_stage:      'Etapa APEX',
    acc_apex_stage_hint: 'fase de la cuenta',
    acc_no_stage:        '— Sin etapa —',
    acc_eval_1:          'Evaluación Fase 1',
    acc_eval_2:          'Evaluación Fase 2',
    acc_funded:          'Funded (Financiada)',
    acc_performance:     'Performance Account',
    acc_environment:     'Entorno',
    acc_demo_env:        'Demo / Evaluación',
    acc_live_env:        'Live / Funded',
    acc_oauth_note_title: '🔐 Sin contraseña — usa OAuth',
    acc_oauth_note_body:  'Tradovate no usa usuario/contraseña por API. Después de crear, presiona Conectar Tradovate para autorizar con tu cuenta APEX.',
    acc_creating:        'Crear cuenta',
    acc_connect_tv:      'Conectar Tradovate',
    acc_tv_connected:    'Tradovate conectado exitosamente.',
    acc_confirm_delete:  '¿Estás seguro de que quieres eliminar esta cuenta? Esta acción no se puede deshacer.',

    // ── CopyGroups ────────────────────────────────────────────────────────────
    grp_title:           'Grupos de Copiado',
    grp_subtitle:        'Cualquier cuenta puede participar en múltiples grupos con roles distintos.',
    grp_tipo_info:       'Tipo de Grupo',
    grp_new:             '+ Nuevo grupo',
    grp_no_groups:       'No hay grupos de copiado. Crea uno nuevo para comenzar.',
    grp_tipo_title:      'Tipo de Grupo',
    grp_dist_title:      'Modo de Distribución',
    grp_ticker:          'Ticker',
    grp_linked:          'vinculada(s)',
    grp_no_dist:         '— no distribuye señales',
    grp_active_tooltip:  'Activo — click para pausar',
    grp_paused_tooltip:  'Pausado — click para activar',
    grp_hide:            'Ocultar',
    grp_linked_accs:     'Cuentas vinculadas',
    grp_copy_accs:       'Cuentas copiadoras',
    grp_add_acc:         '+ Vincular cuenta',
    grp_no_linked:       'Sin cuentas vinculadas aún.',
    grp_account:         'Cuenta',
    grp_risk_pct:        'Riesgo %',
    grp_order:           'Orden',
    grp_remove:          'Quitar',
    grp_edit_title:      'Editar grupo',
    grp_new_title:       'Nuevo grupo de copiado',
    grp_modal_sub:       'El Tipo de Grupo y el Modo de distribución determinan cómo se seleccionan y reciben señales las cuentas.',
    grp_name_label:      'Nombre *',
    grp_tipo_label:      'Tipo de Grupo',
    grp_master_acc:      'Cuenta Master *',
    grp_master_acc_hint: '— cuenta que genera las señales vía TradingView',
    grp_select_acc:      'Seleccionar cuenta…',
    grp_ticker_filter:   'Filtro de Ticker',
    grp_ticker_hint:     '— opcional, vacío = todos los símbolos',
    grp_dist_label:      'Modo de distribución',
    grp_order_gen:       'Generación de Órdenes',
    grp_auto_mode:       'Automática',
    grp_auto_sub:        'Envía al broker al llegar la señal',
    grp_manual_mode:     'Manual',
    grp_manual_sub:      'Queda pendiente, tú decides enviar',
    grp_batch_label:     'Tamaño de batch (N)',
    grp_batch_hint:      '— cuentas por señal',
    grp_create:          'Crear grupo',
    grp_follower_title:  'Vincular cuenta copiadora',
    grp_follower_sub:    'Cuenta que replicará las señales del grupo aplicando su propio riesgo y reglas.',
    grp_risk_hint:       '— multiplicador sobre las reglas de la cuenta (100 = igual, 50 = mitad)',
    grp_rotate_order:    'Orden de rotación',
    grp_rotate_hint:     '— posición en el turno (para modos rotate / rotate_group)',
    grp_adding:          'Agregando…',
    grp_confirm_remove:  '¿Quitar esta cuenta del grupo?',
    grp_ticker_only:     'Solo procesará señales con ticker',
    grp_name_required:   'El nombre es requerido',
    grp_master_required: 'Selecciona la cuenta master',
    grp_tipo_standard:   'Estándar',
    grp_tipo_readonly:   'Solo lectura',
    grp_tipo_standard_desc: 'Recibe señales del webhook y las reparte a las cuentas vinculadas. Es el tipo que usas el 99% del tiempo.',
    grp_tipo_readonly_desc: 'Solo registra las señales que llegan — NO ejecuta órdenes en ninguna cuenta. Útil para monitorear sin operar.',
    grp_tipo_standard_note: 'Recibe webhook → copia en cuentas vinculadas',
    grp_tipo_readonly_note: 'Solo registra señales, no ejecuta órdenes',
    grp_dist_all_desc:   'Cada señal va a TODAS las cuentas del grupo simultáneamente.',
    grp_dist_all_ex:     'Señal → A, B, C, D, E, F',
    grp_dist_rotate_desc: '1 sola cuenta por señal, turno rotativo. Cada señal llega a la siguiente cuenta.',
    grp_dist_rotate_ex:  'Señal1→A  Señal2→B  Señal3→C  Señal4→A…',
    grp_dist_rgroup_desc: 'Divide las cuentas en bloques de N. Cada señal activa el siguiente bloque.',
    grp_dist_rgroup_ex:  'Señal1→[A,B,C]  Señal2→[D,E,F]  Señal3→[G,H,I]  Señal4→[A,B,C]…',
    grp_dist_batch_desc: 'N cuentas por señal. Prioriza las que llevan más tiempo sin operar (APEX recomendado).',
    grp_dist_batch_ex:   'Señal1→[A,B,C,D]  Señal2→[E,F,G,H]  Señal3→[I,A,B,C]…',

    // ── Day labels ────────────────────────────────────────────────────────────
    day_mon: 'Lun', day_tue: 'Mar', day_wed: 'Mié', day_thu: 'Jue',
    day_fri: 'Vie', day_sat: 'Sáb', day_sun: 'Dom',

    // ── Rules ─────────────────────────────────────────────────────────────────
    rules_title:         'Reglas de Trading',
    rules_account_label: 'Cuenta',
    rules_no_accounts:   'No hay cuentas disponibles.',
    rules_risk_section:  'Configuración de riesgo',
    rules_company:       'Empresa',
    rules_select:        '— Seleccionar —',
    rules_other:         'Otra…',
    rules_stage:         'Etapa de cuenta',
    rules_risk_mode:     'Modo de riesgo',
    rules_fixed_usd:     'USD fijo',
    rules_pct_balance:   '% de balance',
    rules_risk_amount:   'Riesgo fijo (USD)',
    rules_risk_pct:      'Riesgo (% balance)',
    rules_schedule:      'Horario (CT — Chicago Time)',
    rules_allowed_days:  'Días permitidos',
    rules_allowed_sess:  'Sesiones donde SÍ operar',
    rules_no_sessions:   'Sin sesiones — todas las señales serán bloqueadas por horario.',
    rules_add_session:   '+ Agregar sesión',
    rules_blocked_sess:  'Zonas donde NO operar',
    rules_blocked_hint:  '— bloquean aunque estén dentro de una sesión activa',
    rules_no_blocked:    'Sin zonas bloqueadas.',
    rules_add_blocked:   '+ Agregar zona bloqueada',
    rules_protection:    'Proteccion de cuenta',
    rules_max_entries:   'Max entradas por dia',
    rules_no_limit:      'Sin limite',
    rules_max_drawdown:  'Max drawdown diario (%)',
    rules_max_losses:    'Max pérdidas consecutivas',
    rules_max_losses_sub:'(trades cerrados en pérdida)',
    rules_reduce_risk:   'Reducir riesgo tras perdidas',
    rules_reduce_sub:    'Aplica el factor de reduccion al perder consecutivamente',
    rules_reduce_factor: 'Factor de reduccion',
    rules_pause_losses:  'Bloquear tras max pérdidas consecutivas',
    rules_pause_sub:     'Cuando se alcanzan N pérdidas seguidas, la cuenta deja de recibir señales por el resto del día. Al día siguiente se reinicia el contador automáticamente.',
    rules_pause_warning: 'Se bloqueará tras',
    rules_pause_warn2:   'trades perdedores consecutivos',
    rules_crosses_midnight: '↻ cruza medianoche',
    rules_saving:        'Guardando...',
    rules_save:          'Guardar reglas',
    rules_saved_ok:      'Reglas guardadas correctamente.',

    // ── Signals ───────────────────────────────────────────────────────────────
    sig_title:           'Historial de Señales',
    sig_symbol:          'Símbolo',
    sig_from:            'Desde',
    sig_to:              'Hasta',
    sig_status:          'Estado',
    sig_source:          'Origen',
    sig_date:            'Fecha',
    sig_action:          'Acción',
    sig_price:           'Precio',
    sig_strategy:        'Estrategia',
    sig_no_signals:      'No se encontraron señales con los filtros aplicados.',
    sig_orders_gen:      'Órdenes generadas',
    sig_no_orders:       'No hay órdenes para esta señal.',

    // ── Orders ────────────────────────────────────────────────────────────────
    ord_title:           'Bitácora de Trading',
    ord_account:         'Cuenta',
    ord_group:           'Grupo',
    ord_date:            'Entrada',
    ord_entry_price:     'P. Entrada',
    ord_exit_price:      'P. Salida',
    ord_no_group:        'Sin grupo',
    ord_no_orders:       'No hay posiciones con los filtros aplicados.',
    ord_screenshot:      'Screenshot del Trade',
    ord_paste_url:       'Pegar URL de imagen',
    ord_save_url:        'Guardar URL',
    ord_upload_file:     'O subir archivo (PNG / JPG / GIF)',
    ord_no_image:        'Sin imagen adjunta',
    ord_open_tab:        'Abrir en nueva pestaña →',
    ord_remove_image:    'Quitar imagen',
    ord_removing:        'Quitando...',
    ord_image_note:      'La imagen se asocia a la señal — se verá en todas las órdenes de esa señal.',
    ord_add_image:       'Agregar imagen',
    ord_view_image:      'Ver imagen',
    ord_view_edit_image: 'Ver / editar imagen',
    ord_send_order:      'Enviar orden',
    ord_traceability:    'Trazabilidad',
    ord_quantity:        'Cantidad',
    ord_broker:          'Broker',
    ord_entry_p:         'Precio entrada',
    ord_exit_p:          'Precio salida',
    ord_sequence:        'Secuencia:',
    ord_send:            'Enviar',

    // ── AdminDashboard ────────────────────────────────────────────────────────
    admin_title:          'Panel de Administración',
    admin_subtitle:       'Gestión global del sistema',
    admin_plans:          '💎 Planes',
    admin_refresh:        'Actualizar',
    admin_total_users:    'Usuarios totales',
    admin_signals_today:  'Señales hoy',
    admin_orders_today:   'Ordenes hoy',
    admin_active_accounts:'Cuentas activas',
    admin_global_config:  'Configuración Global',
    admin_default_tf:     'TimeFrame predeterminado',
    admin_tf_hint:        'Usado como fallback cuando la señal no incluye timeframe.',
    admin_manual_ttl:     'TTL de orden manual (segundos)',
    admin_ttl_hint:       'Tiempo disponible para aprobar una orden manual antes de que expire. Predeterminado: 60s.',
    admin_saved:          '✓ Guardado',
    admin_users:          'Usuarios',
    admin_registered:     'Registro',
    admin_suspended:      'Suspendido',
    admin_access_denied:  'Acceso denegado',
    admin_access_denied_sub: 'Esta sección es solo para administradores del sistema.',
    admin_user_detail:    'Detalle de usuario',
    admin_no_users:       'No hay usuarios registrados.',
    admin_no_accs:        'Este usuario no tiene cuentas configuradas.',
    accounts:             'Cuentas',

    // ── Settings / Notifications ──────────────────────────────────────────────
    set_title:            'Configuración',
    set_subtitle:         'Notificaciones por email y Telegram',
    set_channels:         'Canales',
    set_email:            'Email',
    set_telegram:         'Telegram',
    set_test:             'Probar',
    set_sent:             '✓ Enviado',
    set_test_error:       '✗ Error',
    set_connected:        'Conectado',
    set_connect_tg:       'Conectar Telegram',
    set_disconnect:       'Desconectar',
    set_waiting:          'Esperando…',
    set_cancel:           'Cancelar',
    set_web_notif:        'Notificaciones Web',
    set_web_notif_sub:    'Alertas del navegador cuando llegue una nueva orden manual de TradingView.',
    set_notif_active:     'Activadas',
    set_notif_active_sub: 'El navegador te avisará cuando llegue una orden manual',
    set_notif_blocked:    'Bloqueadas por el navegador',
    set_notif_blocked_sub:'Para activarlas haz clic en el icono 🔒 de la barra de dirección y permite las notificaciones para este sitio, luego recarga la página.',
    set_activate_notif:   'Activar notificaciones web',
    set_no_support:       'Tu navegador no soporta notificaciones web.',
    set_events:           'Eventos a notificar',
    set_on_fill:          'Orden ejecutada',
    set_on_fill_desc:     'Cuando una orden es filled por el broker',
    set_on_skip:          'Orden saltada',
    set_on_skip_desc:     'SIN_REGLAS, FUERA_DE_HORARIO, SALDO_INSUFICIENTE…',
    set_on_error:         'Error de broker',
    set_on_error_desc:    'Fallo al enviar la orden (después de 3 reintentos)',
    set_on_signal:        'Señal recibida',
    set_on_signal_desc:   'Cada vez que llega un webhook de TradingView',
    set_save_config:      'Guardar configuración',
    set_saving:           'Guardando...',
    set_saved:            '✓ Guardado',
    set_tg_waiting:       'abre Telegram y toca Start en',

    // ── Plans ─────────────────────────────────────────────────────────────────
    plans_title:          'Planes',
    plans_subtitle:       'Elige el plan que mejor se adapta a tu operación',
    plans_period_always:  'siempre',
    plans_period_month:   'mes',
    plans_current:        'Plan actual',
    plans_contact:        '¿Necesitas un plan personalizado para tu firma?',
    plans_contact_us:     'Contáctanos',

    // ── Webhook ───────────────────────────────────────────────────────────────
    wh_title:             'Webhook / TradingView',
    wh_subtitle:          'Configura TradingView para enviar señales automáticas a tus grupos de copiado.',
    wh_your_url:          'Tu URL de Webhook',
    wh_public_badge:      '🌐 Pública · TradingView OK',
    wh_local_badge:       '⚠️ localhost · TradingView NO puede llegar',
    wh_paste_hint:        'Pégala en TradingView → Alert → Notifications → Webhook URL.',
    wh_token_warning:     '⚠️ No compartas esta URL — contiene tu token único de autenticación.',
    wh_not_public_title:  '⚠️ URL no accesible desde TradingView',
    wh_how_title:         '¿Cómo funciona?',
    wh_payload_title:     'Payload JSON',
    wh_actions_title:     'Acciones disponibles',
    wh_tv_vars_title:     'Variables dinámicas de TradingView',
    wh_setup_title:       'Configuración en TradingView',
    wh_required:          '* Requerido',
    wh_field:             'Campo',
    wh_type:              'Tipo',
    wh_description:       'Descripción',
    wh_variable:          'Variable',
    wh_copied:            '✓ Copiado',
    wh_copy:              'Copiar',
    wh_steps_title:       '📋 Cómo crear la alerta en TradingView',

    // ── Reports ───────────────────────────────────────────────────────────────
    rep_title:            'Bitácora y Reportes',
    rep_subtitle:         'Análisis de rendimiento y estadísticas detalladas',
    rep_coming_in:        'Bitácora disponible en v1.2',
    rep_upcoming:         'Funcionalidades próximas',
    rep_roadmap:          'Roadmap de versiones',
    rep_in_dev:           'Esta sección está en desarrollo activo. Se lanzará en la versión 1.2 del sistema.',

    // ── Login ─────────────────────────────────────────────────────────────────
    login_signin:         'Iniciar sesión',
    login_register:       'Registrarse',
    login_email:          'Email',
    login_password:       'Password',
    login_enter:          'Entrar',
    login_create_acc:     'Crear cuenta',
    login_subtitle:       'Sistema de Copy Trading para Futuros',
    login_loading:        'Cargando...',
    login_success:        '¡Cuenta creada! Revisa tu email para confirmar.',

    // ── Change Password Modal ─────────────────────────────────────────────────
    pwd_title:            'Cambiar contraseña',
    pwd_new:              'Nueva contraseña',
    pwd_new_placeholder:  'Mínimo 8 caracteres',
    pwd_confirm:          'Confirmar contraseña',
    pwd_confirm_placeholder: 'Repite la contraseña',
    pwd_min_chars:        'Mínimo 8 caracteres',
    pwd_no_match:         'Las contraseñas no coinciden',
    pwd_updated:          '✓ Contraseña actualizada',
    pwd_saving:           'Guardando...',
    pwd_update:           'Actualizar',

    // ── Manual Panel ──────────────────────────────────────────────────────────
    man_title:            'Panel Manual',
    man_copy_group:       'Grupo de copiado',
    man_symbol:           'Símbolo',
    man_timeframe:        'TimeFrame',
    man_sl:               'Stop Loss',
    man_tp:               'Take Profit',
    man_sl_optional:      'Stop Loss (opcional)',
    man_tp_optional:      'Take Profit (opcional)',
    man_action:           'Acción',
    man_pending_orders:   'Órdenes pendientes',
    man_session_log:      'Log de sesión',
    man_no_pending:       'Sin órdenes pendientes',
    man_no_session:       'Sin actividad en esta sesión',
    man_time:             'Hora',
    man_group:            'Grupo',
    man_result:           'Resultado',
  },

  en: {
    // ── Navigation ────────────────────────────────────────────────────────────
    nav_dashboard:   'Dashboard',
    nav_manual:      'Manual Panel',
    nav_signals:     'Signals',
    nav_orders:      'Orders',
    nav_reports:     'Reports',
    nav_groups:      'Copy Groups',
    nav_accounts:    'Accounts',
    nav_rules:       'Risk Rules',
    nav_webhook:     'Webhook / TV',
    nav_notifications: 'Notifications',
    nav_plans:       'Plans',
    nav_admin:       'Admin',
    nav_config:      'Settings',
    nav_change_pwd:  'Change password',
    nav_logout:      'Sign out',

    // ── TopActionBar section titles ────────────────────────────────────────────
    section_dashboard_title:    'Dashboard',
    section_dashboard_sub:      'Account overview, signals and execution',
    section_signals_title:      'Signals',
    section_signals_sub:        'Received entries and traceability per event',
    section_orders_title:       'Trade Log',
    section_orders_sub:         'Execution history by account and group',
    section_manual_title:       'Manual Panel',
    section_manual_sub:         'Manage pending manual orders',
    section_reports_title:      'Reports',
    section_reports_sub:        'Performance metrics and execution quality',
    section_settings_title:     'Notifications',
    section_settings_sub:       'Channels, alerts and preferences',
    section_groups_title:       'Copy Groups',
    section_groups_sub:         'Copy groups and signal distribution',
    section_accounts_title:     'Accounts',
    section_accounts_sub:       'Broker account connection and configuration',
    section_rules_title:        'Risk Rules',
    section_rules_sub:          'Exposure limits and position management',
    section_webhook_title:      'Webhook / TV',
    section_webhook_sub:        'Configuration of external signal sources',
    section_plans_title:        'Plans',
    section_plans_sub:          'Subscription configuration and limits',
    section_admin_title:        'Admin',
    section_admin_sub:          'System configuration and users',

    // ── Health states ─────────────────────────────────────────────────────────
    health_ok:       'System stable',
    health_degraded: 'Degraded mode',
    health_down:     'API not responding',
    health_checking: 'Checking...',
    last_signal_label: 'Last signal',

    // ── Common ────────────────────────────────────────────────────────────────
    save:            'Save',
    cancel:          'Cancel',
    close:           'Close',
    delete:          'Delete',
    edit:            'Edit',
    new:             'New',
    update:          'Update',
    loading:         'Loading...',
    no_data:         'No data',
    error:           'Error',
    success:         'Success',
    refresh:         'Refresh',
    refreshing:      'Updating...',
    saving:          'Saving...',
    saved:           'Saved',
    confirm_delete:  'Confirm deletion',
    cannot_undo:     'This action cannot be undone.',
    are_you_sure:    'Are you sure you want to delete this account?',
    previous:        'Previous',
    next:            'Next',
    page:            'Page',
    all:             'All',
    all_f:           'All',
    active:          'Active',
    inactive:        'Inactive',
    status:          'Status',
    name:            'Name',
    type:            'Type',
    environment:     'Environment',
    balance:         'Balance',
    actions:         'Actions',
    send:            'Send',
    connect:         'Connect',
    sending:         'Sending...',
    updated:         'Updated',
    see_all:         'See all →',
    see_history:     'See history →',
    create_account:  'Create account',
    add:             'Add',

    // ── Status badges ─────────────────────────────────────────────────────────
    status_active:    'Active',
    status_inactive:  'Inactive',
    status_paused:    'Paused',
    status_no_token:  'No token',
    status_connected: 'Connected',
    status_filled:    'Filled',
    status_pending:   'Queued',
    status_sent:      'Sent',
    status_skipped:   'Skipped',
    status_error:     'Error',
    status_open:      'OPEN',
    status_closed:    'CLOSED',
    status_awaiting:  'PENDING',
    status_rejected:  'Rejected',

    // ── Dashboard ─────────────────────────────────────────────────────────────
    dash_day_summary:     'Daily Summary',
    dash_updated_at:      'Updated',
    dash_manual_panel:    '+ Manual Panel',
    dash_kpi_active_accs: 'Active accounts',
    dash_kpi_active_sub:  'Ready to trade',
    dash_kpi_signals:     'Signals today',
    dash_kpi_signals_sub: 'Received entries',
    dash_kpi_orders:      'Orders executed',
    dash_kpi_orders_sub:  'Filled today',
    dash_kpi_pnl:         'Daily P&L',
    dash_kpi_pnl_pos:     'Positive bias',
    dash_kpi_pnl_neg:     'Negative bias',
    dash_accounts_title:  'Accounts & connection',
    dash_signals_title:   'Recent signals',
    dash_no_accounts:     'No accounts configured',
    dash_no_signals:      'No recent signals yet.',
    dash_alert_paused:    'Accounts paused by risk',
    dash_alert_no_token:  'Accounts without broker connection',
    dash_alert_no_accs:   'No accounts configured',
    dash_alert_no_accs_body: 'Create an account to start processing signals.',

    // ── Accounts ─────────────────────────────────────────────────────────────
    acc_title:           'Accounts',
    acc_new:             '+ New account',
    acc_tv_user:         'TV User',
    acc_stage:           'Stage',
    acc_no_accounts:     'No accounts. Create a new account to get started.',
    acc_edit_title:      'Edit account',
    acc_new_title:       'New account',
    acc_name_label:      'Name *',
    acc_type_label:      'Account type',
    acc_paper_title:     'Paper Trading',
    acc_paper_sub:       'No real broker · Instant',
    acc_tv_requires:     'Requires OAuth',
    acc_balance_label:   'Initial balance ($)',
    acc_paper_note:      'Simulated account — orders execute instantly without a real broker.',
    acc_tv_username:     'Tradovate Username / Email',
    acc_account_number:  'Account Number',
    acc_account_number_hint: 'Numeric ID in Tradovate',
    acc_account_spec:    'Account Spec',
    acc_apex_stage:      'APEX Stage',
    acc_apex_stage_hint: 'account phase',
    acc_no_stage:        '— No stage —',
    acc_eval_1:          'Evaluation Phase 1',
    acc_eval_2:          'Evaluation Phase 2',
    acc_funded:          'Funded',
    acc_performance:     'Performance Account',
    acc_environment:     'Environment',
    acc_demo_env:        'Demo / Evaluation',
    acc_live_env:        'Live / Funded',
    acc_oauth_note_title: '🔐 No password — uses OAuth',
    acc_oauth_note_body:  'Tradovate does not use username/password via API. After creating, press Connect Tradovate to authorize with your APEX account.',
    acc_creating:        'Create account',
    acc_connect_tv:      'Connect Tradovate',
    acc_tv_connected:    'Tradovate connected successfully.',
    acc_confirm_delete:  'Are you sure you want to delete this account? This action cannot be undone.',

    // ── CopyGroups ────────────────────────────────────────────────────────────
    grp_title:           'Copy Groups',
    grp_subtitle:        'Any account can participate in multiple groups with different roles.',
    grp_tipo_info:       'Group Type',
    grp_new:             '+ New group',
    grp_no_groups:       'No copy groups. Create a new one to get started.',
    grp_tipo_title:      'Group Type',
    grp_dist_title:      'Distribution Mode',
    grp_ticker:          'Ticker',
    grp_linked:          'linked',
    grp_no_dist:         '— does not distribute signals',
    grp_active_tooltip:  'Active — click to pause',
    grp_paused_tooltip:  'Paused — click to activate',
    grp_hide:            'Hide',
    grp_linked_accs:     'Linked accounts',
    grp_copy_accs:       'Copier accounts',
    grp_add_acc:         '+ Link account',
    grp_no_linked:       'No linked accounts yet.',
    grp_account:         'Account',
    grp_risk_pct:        'Risk %',
    grp_order:           'Order',
    grp_remove:          'Remove',
    grp_edit_title:      'Edit group',
    grp_new_title:       'New copy group',
    grp_modal_sub:       'Group Type and Distribution Mode determine how accounts are selected and receive signals.',
    grp_name_label:      'Name *',
    grp_tipo_label:      'Group Type',
    grp_master_acc:      'Master Account *',
    grp_master_acc_hint: '— account that generates signals via TradingView',
    grp_select_acc:      'Select account…',
    grp_ticker_filter:   'Ticker Filter',
    grp_ticker_hint:     '— optional, empty = all symbols',
    grp_dist_label:      'Distribution mode',
    grp_order_gen:       'Order Generation',
    grp_auto_mode:       'Automatic',
    grp_auto_sub:        'Sends to broker when signal arrives',
    grp_manual_mode:     'Manual',
    grp_manual_sub:      'Stays pending, you decide to send',
    grp_batch_label:     'Batch size (N)',
    grp_batch_hint:      '— accounts per signal',
    grp_create:          'Create group',
    grp_follower_title:  'Link copier account',
    grp_follower_sub:    'Account that will replicate group signals applying its own risk and rules.',
    grp_risk_hint:       '— multiplier on account rules (100 = same, 50 = half)',
    grp_rotate_order:    'Rotation order',
    grp_rotate_hint:     '— position in rotation (for rotate / rotate_group modes)',
    grp_adding:          'Adding…',
    grp_confirm_remove:  'Remove this account from the group?',
    grp_ticker_only:     'Will only process signals with ticker',
    grp_name_required:   'Name is required',
    grp_master_required: 'Select master account',
    grp_tipo_standard:   'Standard',
    grp_tipo_readonly:   'Read-only',
    grp_tipo_standard_desc: 'Receives webhook signals and distributes them to linked accounts. This is the type you use 99% of the time.',
    grp_tipo_readonly_desc: 'Only records incoming signals — does NOT execute orders on any account. Useful for monitoring without trading.',
    grp_tipo_standard_note: 'Receives webhook → copies to linked accounts',
    grp_tipo_readonly_note: 'Only records signals, does not execute orders',
    grp_dist_all_desc:   'Each signal goes to ALL accounts in the group simultaneously.',
    grp_dist_all_ex:     'Signal → A, B, C, D, E, F',
    grp_dist_rotate_desc: '1 account per signal, round-robin rotation. Each signal goes to the next account.',
    grp_dist_rotate_ex:  'Signal1→A  Signal2→B  Signal3→C  Signal4→A…',
    grp_dist_rgroup_desc: 'Divides accounts into blocks of N. Each signal activates the next block.',
    grp_dist_rgroup_ex:  'Signal1→[A,B,C]  Signal2→[D,E,F]  Signal3→[G,H,I]  Signal4→[A,B,C]…',
    grp_dist_batch_desc: 'N accounts per signal. Prioritizes accounts that have gone longest without trading (APEX recommended).',
    grp_dist_batch_ex:   'Signal1→[A,B,C,D]  Signal2→[E,F,G,H]  Signal3→[I,A,B,C]…',

    // ── Day labels ────────────────────────────────────────────────────────────
    day_mon: 'Mon', day_tue: 'Tue', day_wed: 'Wed', day_thu: 'Thu',
    day_fri: 'Fri', day_sat: 'Sat', day_sun: 'Sun',

    // ── Rules ─────────────────────────────────────────────────────────────────
    rules_title:         'Trading Rules',
    rules_account_label: 'Account',
    rules_no_accounts:   'No accounts available.',
    rules_risk_section:  'Risk configuration',
    rules_company:       'Company',
    rules_select:        '— Select —',
    rules_other:         'Other…',
    rules_stage:         'Account stage',
    rules_risk_mode:     'Risk mode',
    rules_fixed_usd:     'Fixed USD',
    rules_pct_balance:   '% of balance',
    rules_risk_amount:   'Fixed risk (USD)',
    rules_risk_pct:      'Risk (% balance)',
    rules_schedule:      'Schedule (CT — Chicago Time)',
    rules_allowed_days:  'Allowed days',
    rules_allowed_sess:  'Sessions where trading IS allowed',
    rules_no_sessions:   'No sessions — all signals will be blocked by schedule.',
    rules_add_session:   '+ Add session',
    rules_blocked_sess:  'Zones where trading is NOT allowed',
    rules_blocked_hint:  '— block even if within an active session',
    rules_no_blocked:    'No blocked zones.',
    rules_add_blocked:   '+ Add blocked zone',
    rules_protection:    'Account protection',
    rules_max_entries:   'Max entries per day',
    rules_no_limit:      'No limit',
    rules_max_drawdown:  'Max daily drawdown (%)',
    rules_max_losses:    'Max consecutive losses',
    rules_max_losses_sub:'(closed trades at a loss)',
    rules_reduce_risk:   'Reduce risk after losses',
    rules_reduce_sub:    'Applies reduction factor when losing consecutively',
    rules_reduce_factor: 'Reduction factor',
    rules_pause_losses:  'Block after max consecutive losses',
    rules_pause_sub:     'When N consecutive losses are reached, the account stops receiving signals for the rest of the day. Counter resets automatically the next day.',
    rules_pause_warning: 'Will block after',
    rules_pause_warn2:   'consecutive losing trades',
    rules_crosses_midnight: '↻ crosses midnight',
    rules_saving:        'Saving...',
    rules_save:          'Save rules',
    rules_saved_ok:      'Rules saved successfully.',

    // ── Signals ───────────────────────────────────────────────────────────────
    sig_title:           'Signal History',
    sig_symbol:          'Symbol',
    sig_from:            'From',
    sig_to:              'To',
    sig_status:          'Status',
    sig_source:          'Source',
    sig_date:            'Date',
    sig_action:          'Action',
    sig_price:           'Price',
    sig_strategy:        'Strategy',
    sig_no_signals:      'No signals found with the applied filters.',
    sig_orders_gen:      'Generated orders',
    sig_no_orders:       'No orders for this signal.',

    // ── Orders ────────────────────────────────────────────────────────────────
    ord_title:           'Trade Log',
    ord_account:         'Account',
    ord_group:           'Group',
    ord_date:            'Entry',
    ord_entry_price:     'Entry P.',
    ord_exit_price:      'Exit P.',
    ord_no_group:        'No group',
    ord_no_orders:       'No positions with the applied filters.',
    ord_screenshot:      'Trade Screenshot',
    ord_paste_url:       'Paste image URL',
    ord_save_url:        'Save URL',
    ord_upload_file:     'Or upload file (PNG / JPG / GIF)',
    ord_no_image:        'No attached image',
    ord_open_tab:        'Open in new tab →',
    ord_remove_image:    'Remove image',
    ord_removing:        'Removing...',
    ord_image_note:      'The image is associated with the signal — it will appear on all orders for that signal.',
    ord_add_image:       'Add image',
    ord_view_image:      'View image',
    ord_view_edit_image: 'View / edit image',
    ord_send_order:      'Send order',
    ord_traceability:    'Traceability',
    ord_quantity:        'Quantity',
    ord_broker:          'Broker',
    ord_entry_p:         'Entry price',
    ord_exit_p:          'Exit price',
    ord_sequence:        'Sequence:',
    ord_send:            'Send',

    // ── AdminDashboard ────────────────────────────────────────────────────────
    admin_title:          'Administration Panel',
    admin_subtitle:       'Global system management',
    admin_plans:          '💎 Plans',
    admin_refresh:        'Refresh',
    admin_total_users:    'Total users',
    admin_signals_today:  'Signals today',
    admin_orders_today:   'Orders today',
    admin_active_accounts:'Active accounts',
    admin_global_config:  'Global Configuration',
    admin_default_tf:     'Default TimeFrame',
    admin_tf_hint:        'Used as fallback when the signal does not include a timeframe.',
    admin_manual_ttl:     'Manual order TTL (seconds)',
    admin_ttl_hint:       'Time available to approve a manual order before it expires. Default: 60s.',
    admin_saved:          '✓ Saved',
    admin_users:          'Users',
    admin_registered:     'Registered',
    admin_suspended:      'Suspended',
    admin_access_denied:  'Access denied',
    admin_access_denied_sub: 'This section is for system administrators only.',
    admin_user_detail:    'User detail',
    admin_no_users:       'No registered users.',
    admin_no_accs:        'This user has no accounts configured.',
    accounts:             'Accounts',

    // ── Settings / Notifications ──────────────────────────────────────────────
    set_title:            'Settings',
    set_subtitle:         'Email and Telegram notifications',
    set_channels:         'Channels',
    set_email:            'Email',
    set_telegram:         'Telegram',
    set_test:             'Test',
    set_sent:             '✓ Sent',
    set_test_error:       '✗ Error',
    set_connected:        'Connected',
    set_connect_tg:       'Connect Telegram',
    set_disconnect:       'Disconnect',
    set_waiting:          'Waiting…',
    set_cancel:           'Cancel',
    set_web_notif:        'Web Notifications',
    set_web_notif_sub:    'Browser alerts when a new manual order arrives from TradingView.',
    set_notif_active:     'Enabled',
    set_notif_active_sub: 'Browser will notify you when a manual order arrives',
    set_notif_blocked:    'Blocked by browser',
    set_notif_blocked_sub:'To enable, click the 🔒 icon in the address bar and allow notifications for this site, then reload.',
    set_activate_notif:   'Enable web notifications',
    set_no_support:       'Your browser does not support web notifications.',
    set_events:           'Events to notify',
    set_on_fill:          'Order filled',
    set_on_fill_desc:     'When an order is filled by the broker',
    set_on_skip:          'Order skipped',
    set_on_skip_desc:     'NO_RULES, OUT_OF_SCHEDULE, INSUFFICIENT_BALANCE…',
    set_on_error:         'Broker error',
    set_on_error_desc:    'Failed to send order (after 3 retries)',
    set_on_signal:        'Signal received',
    set_on_signal_desc:   'Every time a TradingView webhook arrives',
    set_save_config:      'Save settings',
    set_saving:           'Saving...',
    set_saved:            '✓ Saved',
    set_tg_waiting:       'open Telegram and tap Start on',

    // ── Plans ─────────────────────────────────────────────────────────────────
    plans_title:          'Plans',
    plans_subtitle:       'Choose the plan that best fits your operation',
    plans_period_always:  'forever',
    plans_period_month:   'month',
    plans_current:        'Current plan',
    plans_contact:        'Need a custom plan for your firm?',
    plans_contact_us:     'Contact us',

    // ── Webhook ───────────────────────────────────────────────────────────────
    wh_title:             'Webhook / TradingView',
    wh_subtitle:          'Configure TradingView to send automatic signals to your copy groups.',
    wh_your_url:          'Your Webhook URL',
    wh_public_badge:      '🌐 Public · TradingView OK',
    wh_local_badge:       '⚠️ localhost · TradingView CANNOT reach',
    wh_paste_hint:        'Paste it in TradingView → Alert → Notifications → Webhook URL.',
    wh_token_warning:     '⚠️ Do not share this URL — it contains your unique authentication token.',
    wh_not_public_title:  '⚠️ URL not accessible from TradingView',
    wh_how_title:         'How does it work?',
    wh_payload_title:     'JSON Payload',
    wh_actions_title:     'Available actions',
    wh_tv_vars_title:     'TradingView dynamic variables',
    wh_setup_title:       'Setup in TradingView',
    wh_required:          '* Required',
    wh_field:             'Field',
    wh_type:              'Type',
    wh_description:       'Description',
    wh_variable:          'Variable',
    wh_copied:            '✓ Copied',
    wh_copy:              'Copy',
    wh_steps_title:       '📋 How to create the alert in TradingView',

    // ── Reports ───────────────────────────────────────────────────────────────
    rep_title:            'Trade Log & Reports',
    rep_subtitle:         'Performance analysis and detailed statistics',
    rep_coming_in:        'Trade log available in v1.2',
    rep_upcoming:         'Upcoming features',
    rep_roadmap:          'Version roadmap',
    rep_in_dev:           'This section is under active development. It will be released in version 1.2.',

    // ── Login ─────────────────────────────────────────────────────────────────
    login_signin:         'Sign in',
    login_register:       'Sign up',
    login_email:          'Email',
    login_password:       'Password',
    login_enter:          'Enter',
    login_create_acc:     'Create account',
    login_subtitle:       'Copy Trading System for Futures',
    login_loading:        'Loading...',
    login_success:        'Account created! Check your email to confirm.',

    // ── Change Password Modal ─────────────────────────────────────────────────
    pwd_title:            'Change password',
    pwd_new:              'New password',
    pwd_new_placeholder:  'Minimum 8 characters',
    pwd_confirm:          'Confirm password',
    pwd_confirm_placeholder: 'Repeat the password',
    pwd_min_chars:        'Minimum 8 characters',
    pwd_no_match:         'Passwords do not match',
    pwd_updated:          '✓ Password updated',
    pwd_saving:           'Saving...',
    pwd_update:           'Update',

    // ── Manual Panel ──────────────────────────────────────────────────────────
    man_title:            'Manual Panel',
    man_copy_group:       'Copy group',
    man_symbol:           'Symbol',
    man_timeframe:        'TimeFrame',
    man_sl:               'Stop Loss',
    man_tp:               'Take Profit',
    man_sl_optional:      'Stop Loss (optional)',
    man_tp_optional:      'Take Profit (optional)',
    man_action:           'Action',
    man_pending_orders:   'Pending orders',
    man_session_log:      'Session log',
    man_no_pending:       'No pending orders',
    man_no_session:       'No activity in this session',
    man_time:             'Time',
    man_group:            'Group',
    man_result:           'Result',
  },
} as const

type TranslationsType = typeof translations['es']

interface LangCtx {
  lang: Lang
  setLang: (l: Lang) => void
  t: (key: keyof TranslationsType) => string
}

const LanguageContext = createContext<LangCtx>({
  lang: 'es',
  setLang: () => {},
  t: (k) => k as string,
})

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    const saved = localStorage.getItem('stp_lang')
    return (saved === 'en' || saved === 'es') ? saved : 'es'
  })

  function setLang(l: Lang) {
    setLangState(l)
    localStorage.setItem('stp_lang', l)
  }

  function t(key: keyof TranslationsType): string {
    return (translations[lang] as Record<string, string>)[key as string]
      ?? (translations['es'] as Record<string, string>)[key as string]
      ?? (key as string)
  }

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  return useContext(LanguageContext)
}
